package stickers

const DancingAnimeGirl string = "CAACAgQAAxkBAAIBXmNWH271PaOcJK-_yd2NLT7lXIoxAAK2BwACS2nuEMYCMo5r4qvlKgQ"
const QuestioningAnimeGitl string = "CAACAgQAAxkBAAMJY8JKIXBi2u08zBfLNY_kC0Vry5MAAoUAA0tp7hC4P9UxjWqS_y0E"
