name: Publish new version

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build a Docker image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ultima
        tags: latest
        containerfiles: |
          ./Dockerfile
        
    - name: Push to Container registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: cr.yandex/crp59r7snaughmoe7iqk
        username: oauth
        password: ${{ secrets.REGISTRY_PASSWORD }
