name: Publish new version

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build a Docker image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ultima
        tags: latest
        containerfiles: |
          ./Dockerfile
        
    - name: Push to Container registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: cr.yandex/crp59r7snaughmoe7iqk
        username: oauth
        password: ${{ secrets.REGISTRY_PASSWORD }}
  restart:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host ultima
          User kon3gor
          HostName $SSH_HOST
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_KEY: ${{ secrets.PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.HOST }}

    - name: Restart bot
      run: |
        ssh -vvv -i ~/.ssh/staging.key ultima './run'

